### ISSUE TITLE
Pouvoir traduire l'interface d'OnaGUI en anglais

### ISSUE THREAD

**Issue by tfrancart** [lmazuel/onagui#12]
(et dans d'autres langues également, avec les fichiers de ressources qui vont bien)

**Comment by lmazuel** [comment]
C'est [deja le cas](https://github.com/lmazuel/onagui/blob/master/src/main/resources/messages.properties) non?

**Comment by tfrancart** [comment]
OK mais rien dans l'application ne permet de choisir la langue d'affichage ? le choix se fait sur la base de la Locale par défaut de java j'imagine ? pourrait-on avoir un choix de langue de l'application dans un menu ?

**Comment by tfrancart** [comment]
Pourras-tu simplement indiquer le paramètre de lancement permettant de lancer OnaGUI avec une interface en anglais ?

**Comment by lmazuel** [comment]
@tfrancart il faut utiliser la variable d’environnement `ONAGUI_FORCE_LANGUAGE` sur `en`. J'avais oublié que j'avais fait ça...
Donc sur Linux;
```console
export ONAGUI_FORCE_LANGUAGE=en
```
devrait fonctionner

**Comment by tfrancart** [comment]
Ajouter un menu dans l'application pour changer la langue de l'interface : Nouveau menu "Application > Langue > 2 sous-entrées français et anglais".

Modifier la classe fr.onagui.gui.Messages pour pouvoir passer une nouvelle langue et réinitialiser le ResourceBundle
