### ISSUE TITLE
Un concept devient "Rouge" avec avoir supprimé tous ses alignements au lieu de redevenir gris

### ISSUE THREAD

**Issue by tfrancart** [lmazuel/onagui#17]
Quand il y a une correspondance sur un concept, son rond devient vert dans l'arbre.
Quand il n'y a pas de correspondance, son rond reste gris.
Quand il y a une correspondance et que je la supprime, le rond devient rouge; c'est bizarre, je m'attendrais à ce que le rond redeviennent gris. A quoi correspond cet état "rouge" du concept ? faut-il le garder ? est-ce que le rond ne devrait pas redevenir gris ?

**Comment by lmazuel** [comment]
Je pense qu'initialement rouge ca veut dire "non alignable". Il faut que je vérifie, je me souviens plus.

**Comment by tfrancart** [comment]
Non c'est le noir quand on coche la case non alignable.

**Comment by lmazuel** [comment]
Bon ben il faut je regarde alors :)

**Comment by lmazuel** [comment]
@tfrancart Ok, donc les couleurs correspondent aux scores d'alignement:

- 0.75 - 1.0 : Vert
- 0.5 - 0.75 : Jaune
- 0.25 - 0.5 : Orange
- 0.0 - 0.25 : Rouge

Je ne sais pas si cette fonctionnalitée est toujours pertinente, mais dans tous les cas il n'a jamais été question que retirer un alignement le rende rouge. Vu qu'il n'a pas d'alignement, il n'a pas un score de 0.0 comme l'interface le pense mais un score "gris".

Je renomme ce bug de façon corriger ce problème de couleur. Si il faut discuter de la pertinent de ce système de couleur, je veux bien un autre "issue" sur Github :)

**Comment by tfrancart** [comment]
Super. Je n'avais jamais vu ce système de couleur car je n'ai jamais travaillé avec des correspondances à moins de 0.75 ! on peut garder ce système de couleurs comme cela, ce n'est pas gênant.
