### ISSUE TITLE
Améliorer les libellés dans la partie "Lexique" au milieu

### ISSUE THREAD

**Issue by tfrancart** [lmazuel/onagui#18]
"PrefLabels" --> "Libellés préférentiels"
"AltLabels" --> "Synonymes"
"FragURI" --> ?? juste "URI" ? je ne sais pas trop ce qui vient se mettre dans cette zone. Pourrait-on l'afficher plutôt en bas de la partie "Lexique", sous les synonymes ?

**Comment by lmazuel** [comment]
Dans l'uri "http://example.org#myconcet", le fragment d'uri est "myconcept". Regulièrement j'ai vu ce pattern, donc j'ai fini par le proposer pour réduire la longueur de la chaine. Je peux le déplacer c'est pas un problème.

**Comment by tfrancart** [comment]
Toutes les URIs n'ont pas de "#...", certaines se terminent pas "/...". Quel est le comportement dans ce cas ?
Je pense qu'il faut enlever cette partie "FragURI" de l'onglet Lexique. Il pourrait y avoir un autre onglet comme "Metadata" qui afficherait l'URI complète et qui pourrait montrer quelques métadonnées DublinCore comme dcterms:modified + dcterms:created, sur lesquelles OnaGui pourra s'appuyer pour le lancement des alignements uniquement sur les nouveaux concepts.

**Comment by tfrancart** [comment]
Descendre la partie "FragURI" en bas. Modifier les libellés :
"PrefLabels" --> "Libellés préférentiels"
"AltLabels" --> "Synonymes"
"FragURI" --> "URI fragment"

**Comment by tfrancart** [comment]
Classe fr.onagui.gui.LexicalisationPanel
