### ISSUE TITLE
Améliorer la racine dans SKOSContainer pour ne plus avoir "owl:Thing"

### ISSUE THREAD

**Issue by tfrancart** [lmazuel/onagui#34]
Avoir quelque chose de plus explicite comme "All Concept Schemes"

**Comment by lmazuel** [comment]
Celui la est facile :)
https://github.com/lmazuel/onagui/blob/31e73119256e131bc72923d68bb1fa2bc24c04fb/src/main/java/fr/onagui/alignment/container/SKOSContainer.java#L538
