### ISSUE TITLE
When the details panel contains too many information, the alignement table disappears

### ISSUE THREAD

**Issue by tfrancart** [lmazuel/onagui#47]
![detail-table-too-high](https://user-images.githubusercontent.com/2728945/41419961-9ff31532-6ff3-11e8-9bcc-0d4b7f633907.png)

Typically happens when a concept has a lot of synonyms.
I am not sure what the best solution is : a vertical scrollbar, but on which panel : the entire center panel ? or only the details panel under the alignment table ?

**Comment by Dalb** [comment]
when you say "lot of synonyms", I suppose that is for each concepts ? when the thesaurus contains many equivalents rather than (real) synonyms ...A big issue for alignment...
I'm having this problem right now. What to do ? Best.

**Comment by tfrancart** [comment]
This happens when the source or target concept of the correspondance that you select in the table has a lot of labels (prefLabels or altLabels). Unfortunately I don't have any workaround for the moment.
