### ISSUE TITLE
Afficher les notes SKOS des Concepts

### ISSUE THREAD

**Issue by tfrancart** [lmazuel/onagui#8]
Dans la partie centrale, ajouter un onglet “Notes” en plus de “Lexique” et “Commentaires”, qui
affichera les propriétés suivantes (dans cet ordre, de la plus utilisée à la moins utilisée) :
● skos:scopeNote
● skos:definition
● skos:historyNote

L’affichage doit se faire en fonction de la langue d’affichage choisie. Comme pour l’onglet
“Lexique”, on peut afficher côte à côte les notes des 2 concepts choisis.
S’il y a suffisamment de place en hauteur, on peut aussi afficher d’autres notes SKOS :
● skos:changeNote
● skos:example
● skos:editorialNote

**Comment by saubin78** [comment]
Bonjour,
j'ajoute un fichier test en skos:note (je sais que cette propriété n'est pas dans la li
[AnimalDiseasesOntology.zip](https://github.com/lmazuel/onagui/files/726115/AnimalDiseasesOntology.zip)

ste).

**Comment by tfrancart** [comment]
La généricité du nouvel onglet est bien et utile. Quelques remarques :
- Je pense qu'on ne devrait pas voir dans le nouvel onglet Annotations les informations qui s'affichent déjà dans l'onglet Lexique. Il faudrait donc enlever prefLabel et altLabel.
- OnaGUI pourrait gérer par défaut quelques préfixes de namespaces connus (skos:, dcterms:, dc: a minima) de façon à afficher dans la combo-box "dcterms:creator" plutôt que l'URI complète.
- Le fait que la combo-box d'annotations change quand on sélectionne un autre concept qui ne porte pas l'annotation qui était sélectionnée avant est un peu perturbant. Est-ce que ce ne serait pas plus cohérent si la combo-box était initialisée une fois pour toute lors du chargement des vocabulaires avec l'ensemble des propriétés d'annotations (hors prefLabel, altLabel, hiddenLabel) trouvées sur tous les concepts ?

**Comment by lmazuel** [comment]
@tfrancart Ok pour 1 et 2. Par contre j'ai peur du temps que peux prendre 3 à scanner l'ensemble du vocabulaire. Peut-etre que par contre je peux le faire en incrémental, ajouter a box les nouvelles annotations au fur et a mesure que j'en vois des nouvelles?

**Comment by tfrancart** [comment]
Il faut mieux laisser le comportement tel qu'il est maintenant, ce n'est pas prioritaire par rapport à d'autres choses. Je fais un ticket séparé pour cela.
