### ISSUE TITLE
référentiel d'alignement non maintenu

### ISSUE THREAD

**Issue by roumestan** [lmazuel/onagui#88]
Bonjour, 
Il semble que l'adresse qui référence la syntaxe pour les alignements n'est plus maintenue : 
http://knowledgeweb.semanticweb.org/heterogeneity/alignment#
Est-ce qu'il existe une autre URI sur laquelle s'appuyer ? 
Merci

**Comment by tfrancart** [comment]
Bonjour, quel est le problème ? si le problème est "http://knowledgeweb.semanticweb.org/heterogeneity/alignment# renvoie une erreur 404", alors ce n'est en aucun cas un problème et n'enlève en rien le caractère d'identifiant de cette URI. De toutes façons ce n'est pas nous qui maintenons/choisissons cet espace de noms. Si le problème est "je ne sais pas où trouver la documentation pour la syntaxe des alignements" alors elle est ici : https://moex.gitlabpages.inria.fr/alignapi/edoal.html

**Comment by roumestan** [comment]
Effectivement, le problème venait de ma requête SPARQL. Je vous remercie pour le lien vers la doc et pour la maintenance de Onagui qui est vraiment d'une grande aide.
